# Generated by Django 4.2.3 on 2024-05-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_y', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('map_height', models.IntegerField()),
                ('map_width', models.IntegerField()),
                ('jump', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitsuji_tower_map_api.map')),
            ],
        ),
        migrations.CreateModel(
            name='RoomColumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitsuji_tower_map_api.column')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitsuji_tower_map_api.room')),
            ],
        ),
        migrations.CreateModel(
            name='MapRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitsuji_tower_map_api.map')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hitsuji_tower_map_api.room')),
            ],
        ),
    ]
